Feature/powers auth policies
in2workspace/in2-issuer-ui pull request #45
Opened 2024-11-15 13:18 UTC by javieralvarezin2

2024-11-28 14:31 UTC, oriolcanades requested changes

2024-11-28 14:31 UTC, oriolcanades commented on src/app/core/services/credential-procedure.service.ts
Podemos añadir un comentario que justifique porqué hemos comentado el "sign"

2024-11-28 14:31 UTC, oriolcanades commented on src/environments/environment.prod.ts
> +  //firma_credential: window["env"]["firma_credential"] || '/api/v1/sign-credential'
Lo mismo, añadamos un comentario para indicar porqué lo comentamos.

2024-11-28 14:31 UTC, oriolcanades commented on src/assets/env.template.js
> +  //window["env"]["firma_credential"] = "${FIRMA_CREDENTIAL}";
Ibid

2024-11-28 14:31 UTC, oriolcanades commented on src/assets/env.js
> +  //window["env"]["firma_credential"] = "${FIRMA_CREDENTIAL}";
ibid

2024-11-29 07:47 UTC, albertorubioin2 approved these changes

2024-11-29 07:47 UTC, oriolcanades approved these changes
Los comentario pasana  deuda técnica que será resuelta en la v1.2.2

2024-11-29 07:51 UTC, oriolcanades approved these changes

2024-11-29 07:52 UTC, merged